# Generated by Django 5.2.3 on 2025-06-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_submission_is_late_alter_submission_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.IntegerField(default=100, verbose_name='Максимальный балл'),
        ),
    ]
